#%RAML 1.0 DataType
description: 
type: object
properties:
  userId?: string
  cartDate?: string
  itemTotal?: number
  discountTotal?: number
  grandTotal?:  number
  items?:  
    type: array
    items: !include cart-items-array.raml
  adjustments?:
    type: array
    items: !include cart-adjustment.raml
  cartResponse?:
    type: object
    properties:
      orderId?: string
      message?: string  
    
    
  
  
    