#%RAML 1.0 DataType
description: product price array
type: object
properties:
  productId?: string
  productPriceTypeId?: string
  description?: string | nil
  fromDate?: string | nil
  thruDate?: string | nil
  price?: number
  productByProductId?: string | nil
  selected?: boolean