#%RAML 1.0 DataType
description: product promos array
type: object
properties:
  productPromoId?: string
  promoName?: string
  productPromoCode?: string
  useLimitPerCode?: string
  useLimitPerCustomer?: string
  fromDate?: string
  thruDate?: string
  productPromoCond?: string | nil
  productPromoAction?: string | nil
  selected?: string