sap:
  host: "api.stripe.com"
  port: "443"
  path: "v1/invoices"
  auth: "Bearer sk_test_69bOEpfWbnXmJ8CrpbtYkDVT00xCLw9HGT"
  timeout:  "60000"
  
mysql:
  host: "10.26.8.249"
  port: "3306"
  username: "root"
  password: "root"
  db: "e_com_mule_db"