sap:
  host: "api.stripe.com"
  port: "443"
  path: "v1/invoices"
  auth: "Bearer sk_test_q69XflYx3m3impJkpy9JbCR100QOzTTAn3"
  timeout:  "60000"
  
mysql:
  #host: "10.26.10.34"
  host: "10.26.8.249"
  port: "3306"
  username: "root"
  password: "root"
  db: "e_com_mule_db"
  
spring:
  #host: "10.26.10.34"
  host: "10.26.8.249"
  port: "8080"
  cart.path:
    init: "/cart/initialize"
    refresh: "/cart/update"
    search: "/product/search"
  order.path:
    create: "/order/create"
    list: "/order/getOrders"
    getOrder: "/order/getOrder"
  
  