sap:
  host: "api.stripe.com"
  port: "443"
  path: "v1/invoices"
  auth: "Bearer sk_test_q69XflYx3m3impJkpy9JbCR100QOzTTAn3"
  timeout:  "60000"
  
mysql:
  host: "10.26.10.34"
  port: "3306"
  username: "root"
  password: "root"
  db: "e_com_mule_db"